MONGO_URI = 'mongodb://localhost:27017/'
MONGO_CLUSTER = 'ntlms'
MONGO_LMSCLUSTER = 'ntlmsdata'
MONGO_LMSLESSONS = 'ntlessons'
MONGO_LMSCOURSESDATA = 'ntcourses'
MONGO_LMSPROGRESS = 'ntprogress'
MONGO_LMSTASKS = 'nttasks'
MONGO_USERS = 'nt_users'